suorganizer/blog/urls.py
from django.conf.urls import url
from .views import PostArchiveMonth, PostArchiveYear, PostDetail, PostList, PostCreate, PostUpdate, PostDelete

urlpatterns = [
    url(r'^$', 
        PostList.as_view(template_name='blog/post_list.html'),
        name="blog_post_list"),
    url(r'^create/$',
        PostCreate.as_view(),
        name='blog_post_create'
    ),
    url(r'^(?P<year>\d{4})/'
    r'(?P<month>\d{1,2})/'
    r'(?P<slug>[\w\-]+)/$',
    PostDetail.as_view(),
        name="blog_post_detail"),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/'
        r'update/$',
        PostUpdate.as_view(),
        name="blog_post_update"),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/'
        r'delete/$',
        PostDelete.as_view(),
        name="blog_post_delete"
    ),
    url(r'^(?P<year>\d{4})/$',
        PostArchiveYear.as_view(),
        name='blog_post_archive_year'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/$',
        PostArchiveMonth.as_view(),
        name="blog_post_archive_month"
    )
]

suorganizer/suorganizer/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.contrib.auth import urls as auth_urls

from organizer.urls import  (
    startup as startup_urls,
    tag as tag_urls
)
from .views import redirect_root
from contact import urls as contact_urls
from blog import urls as blog_urls
from django.views.generic import RedirectView, TemplateView
from user import urls as user_urls

urlpatterns = [
    url(r'^about/$', TemplateView.as_view(
        template_name='site/about.html'
    ), name='about_site'),
    path('admin/', admin.site.urls),
    url(r'^blog/', include(blog_urls)),
    url(r'^startup/', include(startup_urls)),
    url(r'^tag/', include(tag_urls)),
    url(r'^contact/', include(contact_urls)),
    url(r'^$', RedirectView.as_view(
        pattern_name='blog_post_list',
        permanent=False
    )),
    url(r'^user/', include(user_urls,
        namespace='dj-auth'
        )
    ),
]

# username: sairam, password: sairam

suorganizer/user/urls.py
from django.conf.urls import url
from django.contrib.auth import \
    views as auth_views
from django.contrib.auth.forms import \
    AuthenticationForm
from django.views.generic import RedirectView

app_name = 'user'
urlpatterns = [
    url(r'^$', RedirectView.as_view(
        pattern_name='dj-auth:login',
        permanent=False
    )),
    url(r'^login/$', auth_views.LoginView.as_view(template_name= 'user/login.html'), name='login'),
        
    url(r'^logout/$', auth_views.LogoutView.as_view(template_name =  'user/logged_out.html', extra_context = {
            'form': AuthenticationForm
        }),
        name='logout'),
]

suorganizer/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>
            {% block title %}
            Startup Organizer
            {% endblock %}
        </title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css"
      href="{% static 'site/normalize.css' %}">
    <link rel="stylesheet" type="text/css"
      href="{% static 'site/skeleton.css' %}">
    <link rel="stylesheet" type="text/css"
      href="{% static 'site/style.css' %}">
        {% block head %}
        {% endblock %}
    </head>

    <body>
        <div>
            <div class="status row">
                <div class="offset-by-eight four columns">
                  <ul class="inline">
                    {% if user.is_authenticated %}
                      <li><a href="{% url 'dj-auth:logout' %}?next={{ request.path }}">
                        Log Out</a></li>
                    {% else %}
                      <li><a href="{% url 'dj-auth:login' %}?next={{ request.path }}">
                        Log In</a></li>
                    {% endif %}
                  </ul>
                </div>
              </div>
            <header>
                <img
                   src="{% static 'site/logo.png' %}" alt="Site Logo">
                <h1>
                    Startup Organizer
                </h1>
            </header>
            <nav>
                <ul>
                    <li>
                        <a href="{% url 'blog_post_list' %}">Blog</a>
                    </li>
                    <li>
                        <a href="{% url 'organizer_startup_list' %}">Startups</a>
                    </li>
                    <li>
                        <a href="{% url 'organizer_tag_list' %}">Tags</a>
                    </li>
                    <li>
                        <a href="{% url 'contact' %}">
                            Contact
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'about_site' %}">
                            About
                        </a>
                    </li>
                </ul>
            </nav>
            {% if messages %}
                <div>
                    <div>
                        <ul>
                        {% for message in messages %}
                            {% if message.tags %}
                                <li class="{{ message.tags }}">
                                    </li>
                            {% else %}
                                <li>
                            {% endif %}
                            {{ message }}</li>
                        {% endfor %}
                        </ul>
                    </div>
                </div>
            {% endif %}
            <main>
                {% block content %}
                This is default content!
                {% endblock %}
            </main>
        </div>
        <footer>
            <p>
                &copy; 2022
                <a href="">
                   Sairam Gourishetty
                </a>
            </p>
            <p>
                Created for
                <a href="https://Django-Unleashed.com/">
                    Django Unleashed
                </a>
            </p>
        </footer>
    </body>
</html>