suorganizer/blog/urls.py
from django.conf.urls import url
from .views import PostArchiveMonth, PostArchiveYear, PostDetail, PostList, PostCreate, PostUpdate, PostDelete

urlpatterns = [
    url(r'^$', 
        PostList.as_view(template_name='blog/post_list.html'),
        name="blog_post_list"),
    url(r'^create/$',
        PostCreate.as_view(),
        name='blog_post_create'
    ),
    url(r'^(?P<year>\d{4})/'
    r'(?P<month>\d{1,2})/'
    r'(?P<slug>[\w\-]+)/$',
    PostDetail.as_view(),
        name="blog_post_detail"),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/'
        r'update/$',
        PostUpdate.as_view(),
        name="blog_post_update"),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/'
        r'(?P<slug>[\w\-]+)/'
        r'delete/$',
        PostDelete.as_view(),
        name="blog_post_delete"
    ),
    url(r'^(?P<year>\d{4})/$',
        PostArchiveYear.as_view(),
        name='blog_post_archive_year'),
    url(r'^(?P<year>\d{4})/'
        r'(?P<month>\d{1,2})/$',
        PostArchiveMonth.as_view(),
        name="blog_post_archive_month"
    )
]

suorganizer/suorganizer/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.contrib.auth import urls as auth_urls

from organizer.urls import  (
    startup as startup_urls,
    tag as tag_urls
)
from .views import redirect_root
from contact import urls as contact_urls
from blog import urls as blog_urls
from django.views.generic import RedirectView, TemplateView
from user import urls as user_urls

urlpatterns = [
    url(r'^about/$', TemplateView.as_view(
        template_name='site/about.html'
    ), name='about_site'),
    path('admin/', admin.site.urls),
    url(r'^blog/', include(blog_urls)),
    url(r'^startup/', include(startup_urls)),
    url(r'^tag/', include(tag_urls)),
    url(r'^contact/', include(contact_urls)),
    url(r'^$', RedirectView.as_view(
        pattern_name='blog_post_list',
        permanent=False
    )),
    url(r'^user/', include(user_urls,
        namespace='dj-auth'
        )
    ),
]

# username: sairam, password: sairam

suorganizer/organizer/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Tag(models.Model):
    name = models.CharField(max_length=31, unique=True)
    slug = models.SlugField(max_length=31, unique=True, help_text='A label for URL config. ')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']  # order the instances by name

    def get_absolute_url(self):
        return reverse('organizer_tag_detail', args=(self.slug,))

    def get_update_url(self):
        return reverse(
            'organizer_tag_update', kwargs={'slug': self.slug}
        )
    
    def get_delete_url(self):
        return reverse(
            'organizer_tag_delete', kwargs={'slug': self.slug}
        )

class Startup(models.Model):
    name = models.CharField(max_length=31, db_index=True)   # index automatically in the database
    slug = models.SlugField(max_length=31, unique=True, help_text='A label for URL config. ')   #unique fields are automatically indexed
    description = models.TextField()
    founded_date = models.DateField('date founded')
    contact = models.EmailField()
    website = models.URLField(max_length=255)

    # Each startup will have multiple tags, 
    # and each tag may belong to multiple startups. 
    # This is a many-to-many relationship. 
    # Similarly, each blog post will be 
    # associated with tags via a many-to-many relationship
    tags = models.ManyToManyField(Tag, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        get_latest_by = 'founded_date'
    
    def get_absolute_url(self):
        return reverse('organizer_startup_detail', kwargs={'slug': self.slug})

    def get_update_url(self):
        return reverse(
            'organizer_startup_update', kwargs={'slug': self.slug}
        )
    
    def get_delete_url(self):
        return reverse(
            'organizer_startup_delete', kwargs={'slug': self.slug}
        )
    
    def get_newslink_create_url(self):
        return reverse(
            'organizer_newslink_create',
            kwargs={'startup_slug': self.slug}
        )
    

class NewsLink(models.Model):
    title = models.CharField(max_length=63)
    pub_date = models.DateField('date published')
    link = models.URLField(max_length=255)
    slug = models.SlugField(max_length=63)

    #  A one-to-many relationship pointing news links to startups
    #  A news link may belong to only one startup, 
    #  but a startup may have multiple news links, 
    #  meaning we seek to create a one-to-many relationship. 
    #  A news link points at a startup: 
    #  a news link has a foreign key to a startup.
    startup = models.ForeignKey(Startup, on_delete=models.DO_NOTHING)

    def __str__(self):
        return "{}:{}".format(self.startup, self.title)

    class Meta:
        verbose_name = "news article"   # to change name of class from news link to news article
        ordering = ["-pub_date"]
        get_latest_by = "pub_date"
        unique_together = ('slug', 'startup')

    def get_absolute_url(self):
        return self.startup.get_absolute_url()
    
    def get_update_url(self):
        return reverse(
            'organizer_newslink_update',
            kwargs={
                "startup_slug": self.startup.slug,
                "newslink_slug": self.slug
            }
        )
    
    def get_delete_url(self):
        return reverse(
            'organizer_newslink_delete',
            kwargs={
                "startup_slug": self.startup.slug,
                "newslink_slug": self.slug
            }
        )

suorganizer/organizer/forms.py
from django import forms
from .models import Tag, NewsLink, Startup
from django.core.exceptions import ValidationError
from django.forms.widgets import HiddenInput

class SlugCleanMixin:
    """Mixin class for slug cleaning method"""

    def clean_slug(self):
        new_slug = (
            self.cleaned_data['slug'].lower()
        )
        if new_slug == "create":
            raise ValidationError('Slug may not be "create"')
        return new_slug
class TagForm(SlugCleanMixin, forms.ModelForm):
    class Meta:
        model = Tag
        # fields = "__all__"
        # exclude = ['slug']
        fields = ['name', 'slug']
    
    def clean_name(self):
        return self.cleaned_data['name'].lower()


class NewsLinkForm(SlugCleanMixin, forms.ModelForm):
    class Meta:
        model = NewsLink
        fields = "__all__"

class StartupForm(SlugCleanMixin, forms.ModelForm):
    class Meta:
        model = Startup
        fields = "__all__"

class NewsLinkForm(SlugCleanMixin, forms.ModelForm):
    class Meta:
        model = NewsLink
        fields = "__all__"
        widgets = {'startup': HiddenInput() }

suorganizer/organizer/views.py
from django.shortcuts import (get_object_or_404, redirect, render)

from django.http.response import HttpResponse, Http404, HttpResponseNotFound
from django.urls import reverse, reverse_lazy
from blog.forms import PostForm
from user.decorators import class_login_required, custom_login_required, require_authenticated_permission


from .forms import NewsLinkForm, TagForm, StartupForm
from .models import Startup, Tag, NewsLink
from django.template import loader, Context
from django.views.generic import View

# from .utils import ObjectDeleteMixin, ObjectUpdateMixin
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import DetailView, CreateView, DeleteView, ListView

from core.utils import UpdateView
from .utils import (PageLinksMixin, NewsLinkGetObjectMixin, StartupContextMixin)

from django.contrib.auth.decorators import \
    login_required, permission_required, user_passes_test
from django.utils.decorators import \
    method_decorator
from django.contrib.auth import PermissionDenied

# Create your views here.

def tag_list(request):
    return render(request, 'organizer/tag_list.html', {'tag_list': Tag.objects.all()})

class TagList(PageLinksMixin, ListView):
    paginate_by = 5
    model = Tag
    
class TagPageList(View):
        paginate_by = 5
        template_name = 'organizer/tag_list.html'

        def get(self, request, page_number):
            tags = Tag.objects.all()
            paginator = Paginator(
                tags, self.paginate_by
            )

            try:
                page = paginator.page(page_number)
            except PageNotAnInteger:
                page = paginator.page(1)
            except EmptyPage:
                page = paginator.page(
                    paginator.num_pages
                )
            
            if page.has_previous():
                prev_url = reverse(
                    'organizer_tag_page',
                    args={
                        page.previous_page_number()
                    }
                )
            else:
                prev_url = None
            if page.has_next():
                next_url = reverse(
                    'organizer_tag_page',
                    args={
                        page.next_page_number()
                    }
                )
            else:
                next_url = None
            
            context = {
                'is_paginated': page.has_other_pages(),
                'next_page_url': next_url,
                'paginator': paginator,
                'previous_page_url': prev_url,
                'tag_list': page
            }

            return render(
                request,
                self.template_name,
                context
            )


def tag_detail(request, slug):
    tag = get_object_or_404(Tag, slug__iexact=slug)
    return render(request, 'organizer/tag_detail.html', {'tag': tag})

class StartupDetail(DetailView):
    model = Startup

class TagDetail(DetailView):
    model = Tag

class StartupList(PageLinksMixin, ListView):
    model = Startup
    paginate_by: 5


def startup_detail(request, slug):
    startup = get_object_or_404(Startup, slug__iexact=slug)
    return render(request, 'organizer/startup_detail.html', {'startup': startup})

def tag_create(request):
    if request.method == "POST":
        form = TagForm(request.POST)
        if form.is_valid():
            new_tag = form.save()
            return redirect(new_tag)
        else:
            form = TagForm()
        return render(
            request,
            'organizer/tag_form.html',
            {'form': form}
        )


@require_authenticated_permission(
    'organizer.add_tag'
)
class TagCreate(CreateView):
    form_class = TagForm
    model = Tag


class StartupCreate(CreateView):
    form_class = StartupForm
    model = Startup


class NewsLinkCreate(NewsLinkGetObjectMixin, StartupContextMixin, CreateView):
    form_class = NewsLinkForm
    model = NewsLink

    def get_initial(self):
        startup_slug = self.kwargs.get(
            self.startup_slug_url_kwarg
        )
        self.startup = get_object_or_404(
            Startup, slug__iexact=startup_slug
        )
        initial = {
            self.startup_context_object_name: self.startup
        }
        initial.update(self.initial)
        return initial

class NewsLinkUpdate(NewsLinkGetObjectMixin, StartupContextMixin, UpdateView):
    form_class = NewsLinkForm
    model = NewsLink
    slug_url_kwarg = "newslink_slug"
    template_name_suffix = '_form_update'

@require_authenticated_permission(
    'organizer.change_tag'
)
class TagUpdate(UpdateView):
    form_class = TagForm
    model = Tag

class TagDelete(DeleteView, View):
    model = Tag
    success_url = reverse_lazy(
        'organizer_tag_list'
    )

@require_authenticated_permission(
    'organizer.change_startup'
)
class StartupUpdate(UpdateView):
    form_class = StartupForm
    model = Startup
    template_name_suffix = "_form_update"

class StartupDelete(DeleteView, View):
    model = Startup
    success_url = reverse_lazy(
        'organizer_startup_list'
    )

class NewsLinkDelete(StartupContextMixin, DeleteView):
    model = NewsLink
    slug_url_kwarg = "newslink_slug"
    
    def get(self, request, pk):
        newslink = get_object_or_404(
            NewsLink, pk=pk
        )
        return render(
            request,
            'organizer/'
            'newslink_confirm_delete.html',
            {'newslink': newslink}
        )
    
    def post(self, request, pk):
        newslink = get_object_or_404(
            NewsLink, pk=pk
        )
        startup = newslink.startup
        newslink.delete()
        return redirect(startup)
    
    def get_success_url(self):
        return (
            self.object.startup.get_absolute_url()
        )

def model_list(request, model):
    context_object_name = '{}_list'.format(
        model._meta.model_name
    )
    context = {
        context_object_name: model.objects.all()
    }
    template_name = (
        'organizer/{}_list.html'.format(
            model._meta.model_name
        )
    )
    return render(request, template_name, context)

suorganizer/organizer/templates/organizer/base_organizer.html
{% extends parent_template|default:"base.html" %}

{% block content %}
  <div class="row">
    <section class="eight columns">
      {% block org_content %}
        This is default content!
      {% endblock %}
    </section>
    <section class="desktop four columns">
      {% block create_button %}{% endblock %}
    </section>
  </div>
  {% if is_paginated %}
  <div class="row">
    <div class="twelve columns">
      <ul class="pagination">
        {% if first_page_url %}
          <li>
            <a href="{{ first_page_url }}">
              First
            </a>
          </li>
        {% endif %}
        {% if previous_page_url %}
          <li>
            <a href="{{ previous_page_url }}">
              Previous</a>
          </li>
        {% endif %}
        <li>
          Page {{ page_obj.number }}
          of {{ paginator.num_pages }}
        </li>
        {% if next_page_url %}
          <li>
            <a href="{{ next_page_url }}">
              Next</a>
          </li>
        {% endif %}
        {% if last_page_url %}
          <li>
            <a href="{{ last_page_url }}">
              Last
            </a>
          </li>
        {% endif %}
      </ul>
    </div>
    {% endif %}
{% endblock %}

suorganizer/organizer/templates/organizer/newslink_confirm_delete.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Delete News Article
{% endblock %}

{% block content %}
  <div class="row">
    <div class="offset-by-two eight columns">
      <form
          action="{{ newslink.get_delete_url }}"
          method="post">
        {% csrf_token %}
        <p>
          Are you sure you want to delete link to
          article {{ newslink.name }}?
        </p>
        <a 
          href="{{ newslink.get_absolute_url }}"
          class="button"
        >
          Cancel</a>
        <button type="submit">
          Delete Article Link</button>
      </form>
    </div>
  </div>
{% endblock %}

suorganizer/organizer/templates/organizer/newslink_form.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Link News Article to Startup
{% endblock %}

{% block content %}
    <div class="row">
        <div class="offset-by-two eight columns">
            <form action="{{ startup.get_newslink_create_url }}"
                method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button
                    class="button-primary"
                    type="submit"
                >
                    Link Article
                </button>
            </form>
        </div>
    </div>

{% endblock %}

suorganizer/organizer/templates/organizer/newslink_form_update.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Update News Article
{% endblock %}

{% block content %}
  <div class="row">
    <div class="offset-by-two eight columns">
      <form
          action="{{ newslink.get_update_url }}"
          method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button
            class="button-primary"
            type="submit">
          Update Article Link</button>
      </form>
    </div>
  </div>
{% endblock %}

suorganizer/organizer/templates/organizer/startup_confirm_delete.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Delete Startup
{% endblock %}

{% block content %}
  <div class="row">
    <div class="offset-by-two eight columns">
      <form
          action="{{ startup.get_delete_url }}"
          method="post">
        {% csrf_token %}
        <p>
          Are you sure you want to delete
          startup {{ startup.name }}?
        </p>
        <a
            href="{{ startup.get_absolute_url }}"
            class="button button-primary"
        >
          Cancel</a>
        <button type="submit">Delete Startup</button>
      </form>
    </div>
  </div>
{% endblock %}

suorganizer/organizer/templates/organizer/startup_detail.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - {{ startup.name }}
{% endblock %}

{% block content %}
<article>
  <div class="row">
  <div class="offset-by-two eight columns">
  <h2>{{ startup.name }}</h2>
    <ul class="inline">
        <li>
          <a
              href="{{ startup.get_update_url }}"
              class="button">
            Edit Startup</a></li>
        <li>
          <a
              href="{{ startup.get_delete_url }}"
              class="button">
            Delete Startup</a></li>
    </ul>
  <dl>
    <dt>Date Founded</dt>
      <dd>{{ startup.founded_date|date:"F jS, Y" }}</dd>
    <dt>Website</dt>
      <dd>{{ startup.website|urlize }}</dd>
    <dt>Contact</dt>
      <dd>{{ startup.contact }}</dd>

      <dt>Tag{{ startup.tags.count|pluralize }}</dt>
        {% for tag in startup.tags.all %}
          <dd><a href="{{ tag.get_absolute_url }}">
            {{ tag.name|title }}
          </a></dd>
        {% endfor %}

  </dl>

  {{ startup.description|linebreaks }}
  </div></div> <!-- row -->

  {% if startup.newslink_set.all or startup.blog_posts.all %}
    <div class="row">

      {% if startup.newslink_set.all %}
        {% if startup.blog_posts.all  %}
          <section class="meta offset-by-two one-third column">
        {% else %}
          <section class="meta offset-by-two two-thirds column">
        {% endif %}
            <h3>Recent News</h3>
              <p>
                <a
                    href="{{ startup.get_newslink_create_url }}"
                    class="button">
                  Add Article</a></p>
            <ul>
              {% for newslink in startup.newslink_set.all %}
                <li>
                  <a href="{{ newslink.link }}">
                    {{ newslink.title|title }}</a>
                    <ul class="inline">
                        <li>
                          <a
                              href="{{ newslink.get_update_url }}"
                              class="button">
                            Edit Link</a></li>
                        <li>
                          <a
                              href="{{ newslink.get_delete_url }}"
                              class="button">
                            Delete Link</a></li>
                    </ul>
                </li>
              {% endfor %}
            </ul>
          </section>
      {% endif %}

      {% if startup.blog_posts.all %}
        {% if startup.newslink_set.all %}
          <section class="meta one-third column">
        {% else %}
          <section class="meta offset-by-two two-thirds column">
        {% endif %}
            <h3>Blog Post{{ startup.blog_posts.all|pluralize }}</h3>
            <ul>
              {% for post in startup.blog_posts.all %}
                <li>
                  <a href="{{ post.get_absolute_url }}">
                    {{ post.title|title }}</a>
                </li>
              {% endfor %}
            </ul>
          </section>
      {% endif %}

    </div> <!-- row -->
  {% endif %}

</article>
{% endblock %}

suorganizer/organizer/templates/organizer/startup_form.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Create Startup
{% endblock %}

{% block content %}
  <div>
    <div>
      <form
          action="{% url 'organizer_startup_create' %}"
          method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">
          Create Startup</button>
      </form>
    </div>
  </div>
{% endblock %}

suorganizer/organizer/templates/organizer/startup_form_update.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Update Startup
{% endblock %}

{% block content %}
  <div class="row">
    <div class="offset-by-two eight columns">
      <form
          action="{{ startup.get_update_url }}"
          method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button
          class="button-primary"
          type="submit"
        >
          Update Startup</button>
      </form>
    </div>
  </div>
{% endblock %}

suorganizer/organizer/templates/organizer/startup_list.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Startups
{% endblock %}

{% block create_button %}
    <a
        href="{% url 'organizer_startup_create' %}"
        class="button button-primary">
      Create New Startup</a>
{% endblock %}

{% block org_content %}
  <h2>Startup List</h2>
    <div class="mobile">
      <a
          href="{% url 'organizer_startup_create' %}"
          class="button button-primary">
        Create New Startup</a>
    </div>
  <ul>
    {% for startup in startup_list %}
      <li>
        <a href="{{ startup.get_absolute_url }}">
          {{ startup.name }}</a>
          <ul class="inline">
              <li>
                <a
                    href="{{ startup.get_update_url }}"
                    class="button">
                  Edit Startup</a></li>
              <li>
                <a
                    href="{{ startup.get_delete_url }}"
                    class="button">
                  Delete Startup</a></li>
          </ul>
      </li>
    {% empty %}
      <li><em>No Startups Available</em></li>
    {% endfor %}
  </ul>
{% endblock %}

{% block content_footer %}
  {% if is_paginated %}
    <ul class="pagination">
      {% if previous_page_url %}
        <li>
          <a href="{{ previous_page_url }}">
            Previous</a>
        </li>
      {% endif %}
      <li>
        Page {{ page_obj.number }}
        of {{ paginator.num_pages }}
      </li>
      {% if next_page_url %}
        <li>
          <a href="{{ next_page_url }}">
            Next</a>
        </li>
      {% endif %}
    </ul>
  {% endif %}
{% endblock %}

suorganizer/organizer/templates/organizer/tag_confirm_delete.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Delete Tag
{% endblock %}

{% block content %}

    <div class="row">
        <div class="offset-by-two eight columns">
            <form action="{{ tag.get_delete_url }}"
                method="post">
                {% csrf_token %}
                <p>
                    Are you sure you want to delete tag
                    {{ tag.name }} ?
                </p>
                <a
                    href="{{ tag.get_absolute_url }}"
                    class="button button-primary"
                >
                    Cancel
                </a>
                <button type="submit">Delete Tag</button>
            </form>
        </div>
    </div>

{% endblock %}

suorganizer/organizer/templates/organizer/tag_detail.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - {{ tag.name|title }}
{% endblock %}

{% block org_content %}
  <h2>{{ tag.name|title }}</h2>
    <ul class="inline">
        <li>
          <a
              href="{{ tag.get_update_url }}"
              class="button">
            Edit Tag</a></li>
        <li>
          <a
              href="{{ tag.get_delete_url }}"
              class="button">
            Delete Tag</a></li>
    </ul>
  {% if tag.startup_set.all %}
    <section>
      <h3>Startup{{ tag.startup_set.count|pluralize }}</h3>
      <p>
        Tag is associated with
        {{ tag.startup_set.count }}
        startup{{ tag.startup_set.count|pluralize }}.
      </p>
      <ul>
        {% for startup in tag.startup_set.all %}
          <li><a href="{{ startup.get_absolute_url }}">
            {{ startup.name }}
          </a></li>
        {% endfor %}
      </ul>
    </section>
  {% endif %}
      {% if tag.blog_posts.all %}
        <section>
          <h3>Blog Post{{ tag.blog_posts.count|pluralize }}</h3>
          <ul>
            {% for post in tag.blog_posts.all %}
              <li><a href="{{ post.get_absolute_url }}">
                {{ post.title|title }}
              </a></li>
            {% endfor %}
          </ul>
        </section>
      {% endif %}
      {% if not tag.startup_set.all and not tag.blog_posts.all %}
        <p>This tag is not related to any content.</p>
      {% endif %}
{% endblock %}

suorganizer/organizer/templates/organizer/tag_form.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Create Tag
{% endblock %}

{% block content %}
  <div class="row">
    <div class="offset-by-two eight columns">
      <form
          action="{% url 'organizer_tag_create' %}"
          method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button
            class="button-primary"
            type="submit">
          Create Tag</button>
      </form>
    </div>
  </div>
{% endblock %}

suorganizer/organizer/templates/organizer/tag_form_update.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Update Tag
{% endblock %}

{% block content %}
  <div class="row">
    <div class="offset-by-two eight columns">
      <form
          action="{{ tag.get_update_url }}"
          method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button
            class="button-primary"
            type="submit">
          Update Tag</button>
      </form>
    </div>
  </div>
{% endblock %}

suorganizer/organizer/templates/organizer/tag_list.html
{% extends parent_template|default:"organizer/base_organizer.html" %}

{% block title %}
{{ block.super }} - Tag List
{% endblock %}

{% block create_button %}
    <a
        href="{% url 'organizer_tag_create' %}"
        class="button button-primary">
      Create New Tag</a>
{% endblock %}

{% block org_content %}
  <h2>Tag List</h2>
    <div class="mobile">
      <a
          href="{% url 'organizer_tag_create' %}"
          class="button button-primary">
        Create New Tag</a>
    </div>
  <ul>
    {% for tag in tag_list %}
      <li>
        <a href="{{ tag.get_absolute_url }}">
          {{ tag.name|title }}</a>
          <ul class="inline">
            <li>
              <a
                  href="{{ tag.get_update_url }}"
                  class="button">
                Edit Tag</a></li>
            <li>
              <a
                  href="{{ tag.get_delete_url }}"
                  class="button">
                Delete Tag</a></li>
          </ul>
      </li>
    {% empty %}
      <li><em>There are currently no Tags available.</em></li>
    {% endfor %}
  </ul>
{% endblock %}

{% block content_footer %}
  {% if is_paginated %}
    <ul class="pagination">
      {% if previous_page_url %}
        <li>
          <a href="{{ previous_page_url }}">
            Previous</a>
        </li>
      {% endif %}
      <li>
        Page {{ page_obj.number}}
        of {{ paginator.num_pages }}
      </li>
      {% if next_page_url %}
        <li>
          <a href="{{ next_page_url }}">
            Next</a>
        </li>
      {% endif %}
    </ul>
  {% endif %}
{% endblock %}